# Schema for the configuration files of the geslib module.
geslib.settings:
  type: config_object
  label: 'geslib directory'
  mapping:
    geslib_directory:
      type: string
      label: 'Directory'
