rsvplist.settings:
  type: config_object
  label: RSVP list Content Type Settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types RSVP list Form can display on
      sequence: 
        type: string
        label: Content type