<?php

/**
 * @file
 * selective_better_exposed_filters.module
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function selective_better_exposed_filters_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.selective_better_exposed_filters':
      $text = file_get_contents(__DIR__ . '/README.md');
      return '<pre>' . Html::escape($text) . '</pre>';
  }
  return NULL;
}
