<?php 

/**
 * @file 
 * This file demonstrates how to use hook functions
 */


/**
 * Implements hook_cron().
 */
function starterkit_cron() {
  \Drupal::messenger()->addMessage( t( "Hello from mymodule cron hook! :) :)" ) );
}

/**
 * Implements hook_form_alter().
 */
function starterkit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if( $form_id == 'node_article_edit_form' ) {
    \Drupal::messenger()->addMessage( t( 'Form_id of this form is @id', [ '@id' => $form_id ] ));
    $form['actions']['submit']['#value'] = t("Save this awesome!");
  }
}